/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIdRouteImport } from './routes/patient.$id'
import { Route as ApiFhirSplatRouteImport } from './routes/api/fhir.$'

const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFhirSplatRoute = ApiFhirSplatRouteImport.update({
  id: '/api/fhir/$',
  path: '/api/fhir/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/triage': typeof TriageRoute
  '/patient/$id': typeof PatientIdRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/triage': typeof TriageRoute
  '/patient/$id': typeof PatientIdRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/triage': typeof TriageRoute
  '/patient/$id': typeof PatientIdRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/triage' | '/patient/$id' | '/api/fhir/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/triage' | '/patient/$id' | '/api/fhir/$'
  id: '__root__' | '/' | '/triage' | '/patient/$id' | '/api/fhir/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TriageRoute: typeof TriageRoute
  PatientIdRoute: typeof PatientIdRoute
  ApiFhirSplatRoute: typeof ApiFhirSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fhir/$': {
      id: '/api/fhir/$'
      path: '/api/fhir/$'
      fullPath: '/api/fhir/$'
      preLoaderRoute: typeof ApiFhirSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TriageRoute: TriageRoute,
  PatientIdRoute: PatientIdRoute,
  ApiFhirSplatRoute: ApiFhirSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
